# Generated by Django 3.2.9 on 2021-11-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
