# Generated by Django 3.2.9 on 2021-11-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='critic_name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='desc',
            new_name='review_Score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
        migrations.AddField(
            model_name='review',
            name='review_content',
            field=models.CharField(default=0, max_length=122, verbose_name='name'),
            preserve_default=False,
        ),
    ]
